version: "2"
services:
  minio-server:
    image: quay.io/minio/minio:RELEASE.2022-05-04T07-45-27Z
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001" 
    environment:
      MINIO_ROOT_USER: 'minio-local'
      MINIO_ROOT_PASSWORD: 'minio-local'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data